# Generated by Django 4.2.5 on 2023-09-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sar',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sar',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
